# Generated by Django 3.1.4 on 2020-12-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todomvc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
